{
  "timestamp": "2025-07-20T11:16:01.259165",
  "version": "CHNeoWave v1.1.0-beta",
  "total_tests": 3,
  "passed": 0,
  "failed": 3,
  "errors": 0,
  "timeouts": 0,
  "total_duration": 19.13999843597412,
  "results": {
    "test_launch_gui.py": {
      "status": "failed",
      "duration": 5.834195375442505,
      "output": "============================= test session starts =============================\ncollecting ... collected 3 items\n\ntests_smoke/test_launch_gui.py::TestLaunchGUI::test_gui_startup_simulation ",
      "error": ""
    },
    "test_export_hdf5.py": {
      "status": "failed",
      "duration": 7.862702369689941,
      "output": "============================= test session starts =============================\ncollecting ... collected 4 items\n\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_writer_basic FAILED [ 25%]\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_simulated_acquisition_export FAILED [ 50%]\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_integrity_verification FAILED [ 75%]\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_large_dataset_export FAILED [100%]\n\n================================== FAILURES ===================================\n____________________ TestExportHDF5.test_hdf5_writer_basic ____________________\ntests_smoke\\test_export_hdf5.py:90: in test_hdf5_writer_basic\n    assert 'sha256' in loaded_metadata, \"Hash SHA256 manquant\"\nE   AssertionError: Hash SHA256 manquant\nE   assert 'sha256' in {'channel_names': array(['Channel_1', 'Channel_2', 'Channel_3', 'Channel_4'], dtype=object), 'created_at': '2025-07-20T11:15:49.999253', 'duration': np.float64(2.0), 'fs': np.int64(1000), ...}\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:95: in test_hdf5_writer_basic\n    pytest.fail(f\"Erreur test HDF5Writer basique: {str(e)}\")\nE   Failed: Erreur test HDF5Writer basique: Hash SHA256 manquant\nE   assert 'sha256' in {'channel_names': array(['Channel_1', 'Channel_2', 'Channel_3', 'Channel_4'], dtype=object), 'created_at': '2025-07-20T11:15:49.999253', 'duration': np.float64(2.0), 'fs': np.int64(1000), ...}\n---------------------------- Captured stdout setup ----------------------------\n\\n=== Configuration environnement de test CHNeoWave ===\\nR\\xe9pertoire projet: C:\\\\Users\\\\LEM\\\\Desktop\\\\chneowave\\nR\\xe9pertoire source: C:\\\\Users\\\\LEM\\\\Desktop\\\\chneowave\\\\src\\nPython: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]\\n\\u2713 PyQt5\\n\\u2713 numpy\\n\\u2713 scipy\\n\\u2713 h5py\\n\\u2713 reportlab\\n\\u2713 pyqtgraph\\n=== Environnement de test pr\\xeat ===\n______________ TestExportHDF5.test_simulated_acquisition_export _______________\ntests_smoke\\test_export_hdf5.py:176: in test_simulated_acquisition_export\n    assert f.attrs['fs'] == fs, \"Attribut fs incorrect\"\n           ^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:56: in __getitem__\n    attr = h5a.open(self._id, self._e(name))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nh5py/h5a.pyx:80: in h5py.h5a.open\n    ???\nE   KeyError: \"Unable to synchronously open attribute (can't locate attribute: 'fs')\"\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:187: in test_simulated_acquisition_export\n    pytest.fail(f\"Erreur acquisition/export HDF5: {str(e)}\")\nE   Failed: Erreur acquisition/export HDF5: \"Unable to synchronously open attribute (can't locate attribute: 'fs')\"\n---------------------------- Captured stdout call -----------------------------\nDémarrage acquisition simulée: 5.0s à 32Hz, 8 canaux\nUtilisation de données simulées (fallback)\nDonnées collectées: (160, 8) (5.0s)\nTaille fichier HDF5: 0.02 MB\n------------------------------ Captured log call ------------------------------\nERROR    hrneowave.hw.demo_backend:demo_backend.py:101 Callback de données non défini\n_______________ TestExportHDF5.test_hdf5_integrity_verification _______________\ntests_smoke\\test_export_hdf5.py:217: in test_hdf5_integrity_verification\n    assert is_valid, \"Vérification d'intégrité échouée\"\nE   AssertionError: Vérification d'intégrité échouée\nE   assert False\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:238: in test_hdf5_integrity_verification\n    pytest.fail(f\"Erreur test intégrité HDF5: {str(e)}\")\nE   Failed: Erreur test intégrité HDF5: Vérification d'intégrité échouée\nE   assert False\n__________________ TestExportHDF5.test_large_dataset_export ___________________\ntests_smoke\\test_export_hdf5.py:281: in test_large_dataset_export\n    dataset.resize((new_size, n_channels))\nvenv\\Lib\\site-packages\\h5py\\_hl\\dataset.py:741: in resize\n    self.id.set_extent(size)\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nh5py/h5d.pyx:360: in h5py.h5d.DatasetID.set_extent\n    ???\nE   RuntimeError: Unable to synchronously change a dataset's dimensions (dimension cannot exceed the existing maximal size (new: 2000 max: 1000))\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:300: in test_large_dataset_export\n    pytest.fail(f\"Erreur test large dataset: {str(e)}\")\nE   Failed: Erreur test large dataset: Unable to synchronously change a dataset's dimensions (dimension cannot exceed the existing maximal size (new: 2000 max: 1000))\n-------------------------- Captured stdout teardown ---------------------------\n\n=== Nettoyage environnement de test ===\n=========================== short test summary info ===========================\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_writer_basic\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_simulated_acquisition_export\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_integrity_verification\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_large_dataset_export\n============================== 4 failed in 7.00s ==============================\n",
      "error": ""
    },
    "test_calib_pdf.py": {
      "status": "failed",
      "duration": 5.443100690841675,
      "output": "============================= test session starts =============================\ncollecting ... collected 6 items\n\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_generator_basic PASSED [ 16%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_content_verification FAILED [ 33%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_with_high_quality_calibration PASSED [ 50%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_with_multiple_sensors PASSED [ 66%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_signature_verification FAILED [ 83%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_error_handling FAILED [100%]\n\n================================== FAILURES ===================================\n_________________ TestCalibPDF.test_pdf_content_verification __________________\ntests_smoke\\test_calib_pdf.py:116: in test_pdf_content_verification\n    assert 'CHNeoWave' in pdf_content, \"Titre CHNeoWave manquant\"\nE   AssertionError: Titre CHNeoWave manquant\nE   assert 'CHNeoWave' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73441 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVoQ*\"f3V9e5&M$5LE8@U.CP!8.,G!q27iY.uL8R7HkXSLm/#DTaQbM&jg9rKH=ml]d+c7B6X>fF)`sObO-^hPKA*\"cTZV4GOF=uHf!T3oBtHZ8H8_jzzzzzzzzzzzzzzzzzzzzzzzz!(E79bEn8/2t#!Vs&?TTq3.A?4a$$hl>:cj\\\\Cu?3z!\\'p-lfs7GBM%[42e[fe_MV<L#T91?g]\",AZDV[?01K3\\\\Tz!!(q<55an;b(T\"t+gu[lo&ZlOX&c6\"l,\\\\u3L\"NJ0>./6=r?!t9SAQppgpiK:9E\"_[\\'+tobV+])>WF3i2-.ML8r...dstream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 532\\n>>\\nstream\\nGat=\\'95i<6&AI=/b],qKf/%mE%18qeWY-Kg*-uU6B=3P3BU%oQB5A@;\"o8e!aGT\\'KHk1]rOBbo>IKXoM_YO<7$/,DV$OuJ<]Pj:o#*5;u#XYhi4UP[#nhK!$_$Y+VY\"]V#Yfce%e7O+`c/Y.i\\':=*\\']d0\"F7N$i>`cPn9nY_Xon8;u)Eo!Kn&iL;rBR:9amfrHHO!(D\\'&I@qigON,/r4os^=<d`Fc2\\'n19WYWOp-nH8dr)dYb@/\\\\8I2Hme_0L6OaKM98$LR.ga($BkHbeSCL^Ht`p$*op/9%oG]Of%)2eQ[fVIJ$oW!t8uFpPe4eGGr_/kFm=@8O+j\\\\jn\"*&7Y2t+IeTjBW/sZYY-GpV)13)SgUXfpeT<[MDb:r:KcU[rgQ-o[<-2IADfpk*fCso)\\\\ZPnbGqIYS0^AJ5UV]@_/h\"i(`akL_\\\\`_!+%l`gYCWY3O^E_\\'OhBKs=Ij*go=XFE>osl=:rG$;JaFP>`5=?iE@L,io6u8ZEJF).lTBTUG8]gFTTHpY3\\'0Ph)?\\\\4pmrZs\"~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074278 00000 n \\n0000074727 00000 n \\n0000074995 00000 n \\n0000075064 00000 n \\n0000075348 00000 n \\n0000075414 00000 n \\n0000076795 00000 n \\ntrailer\\n<<\\n/ID \\n[<396ad358b46371d6aa86eff5ff76f1ac><396ad358b46371d6aa86eff5ff76f1ac>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77418\\n%%EOF\\n'\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_calib_pdf.py:137: in test_pdf_content_verification\n    pytest.fail(f\"Erreur vérification contenu PDF: {str(e)}\")\nE   Failed: Erreur vérification contenu PDF: Titre CHNeoWave manquant\nE   assert 'CHNeoWave' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73441 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVoQ*\"f3V9e5&M$5LE8@U.CP!8.,G!q27iY.uL8R7HkXSLm/#DTaQbM&jg9rKH=ml]d+c7B6X>fF)`sObO-^hPKA*\"cTZV4GOF=uHf!T3oBtHZ8H8_jzzzzzzzzzzzzzzzzzzzzzzzz!(E79bEn8/2t#!Vs&?TTq3.A?4a$$hl>:cj\\\\Cu?3z!\\'p-lfs7GBM%[42e[fe_MV<L#T91?g]\",AZDV[?01K3\\\\Tz!!(q<55an;b(T\"t+gu[lo&ZlOX&c6\"l,\\\\u3L\"NJ0>./6=r?!t9SAQppgpiK:9E\"_[\\'+tobV+])>WF3i2-.ML8r...dstream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 532\\n>>\\nstream\\nGat=\\'95i<6&AI=/b],qKf/%mE%18qeWY-Kg*-uU6B=3P3BU%oQB5A@;\"o8e!aGT\\'KHk1]rOBbo>IKXoM_YO<7$/,DV$OuJ<]Pj:o#*5;u#XYhi4UP[#nhK!$_$Y+VY\"]V#Yfce%e7O+`c/Y.i\\':=*\\']d0\"F7N$i>`cPn9nY_Xon8;u)Eo!Kn&iL;rBR:9amfrHHO!(D\\'&I@qigON,/r4os^=<d`Fc2\\'n19WYWOp-nH8dr)dYb@/\\\\8I2Hme_0L6OaKM98$LR.ga($BkHbeSCL^Ht`p$*op/9%oG]Of%)2eQ[fVIJ$oW!t8uFpPe4eGGr_/kFm=@8O+j\\\\jn\"*&7Y2t+IeTjBW/sZYY-GpV)13)SgUXfpeT<[MDb:r:KcU[rgQ-o[<-2IADfpk*fCso)\\\\ZPnbGqIYS0^AJ5UV]@_/h\"i(`akL_\\\\`_!+%l`gYCWY3O^E_\\'OhBKs=Ij*go=XFE>osl=:rG$;JaFP>`5=?iE@L,io6u8ZEJF).lTBTUG8]gFTTHpY3\\'0Ph)?\\\\4pmrZs\"~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074278 00000 n \\n0000074727 00000 n \\n0000074995 00000 n \\n0000075064 00000 n \\n0000075348 00000 n \\n0000075414 00000 n \\n0000076795 00000 n \\ntrailer\\n<<\\n/ID \\n[<396ad358b46371d6aa86eff5ff76f1ac><396ad358b46371d6aa86eff5ff76f1ac>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77418\\n%%EOF\\n'\n________________ TestCalibPDF.test_pdf_signature_verification _________________\ntests_smoke\\test_calib_pdf.py:256: in test_pdf_signature_verification\n    assert hash_short in pdf_content, f\"Hash SHA-256 manquant dans le PDF: {hash_short}\"\nE   AssertionError: Hash SHA-256 manquant dans le PDF: e0aa81a413379ce6\nE   assert 'e0aa81a413379ce6' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73437 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVoQ*\"f3V9m\"jk4oM_3+,#tWc/Hc4;\\'9snf_1kjPXoX5I8O<_`6\\'5J?#VDUo6OaSf\"Hnl\\'ZTJ2n\\\\MtJ8ATs?oalL+LB:h;U4*U/K4n%h*H$=1h,QIfEzzzzzzzzzzzzzzzzzzzzzzzzJ<J*5\\'e:V+SG;9>J#_=e_TC\\'ISM=UYoenop>j]6*z!2+VGCtV^`9UU5\"l<V,O=m`p;cIfC3h;$f>[r7n0SZR\\'Bz!!$sYn%SZOA]\")K(u)]Fku,cp260`XG3$`,@VjUHD;2Lqr_K%DdGYj!DVRe.V/bP88P)LmdNrOZ<3UK/;JQ#...N~>endstream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 532\\n>>\\nstream\\nGat=\\'95i<6&AI=/b]/P?n\\'(R?2^jn3W_/(<E9P84m+!;cTi&85+5<mN/l7G*OXs-HchHpA!mF)Um72\\\\N/Z^T3LnRO.8gnAViBuAT20A3W?8/Vbj[a(P.::8rdMq.%WnPDJ$6uZ7:2SRKdl`)M3^K<3!M)ZU3mHlYeh0Ko4t>U*7!LpRT5m)h)&C557T&:[mdCVU.3HAS4Ym@eL91Y\\':\"d=pD6cQU:n@9==YXQk<O\"\\'#=.a]kI96u#KU]l(.lGS`]0e]5p)CAWMB1$*7/MYT#nRoG@dE\\\\?3%T#NCYi[AX1.8nc)+t\"(T7cnLaMq(.ILL,U@m`]OHQskWh)&%jMTo=B/<(9OQN.IVJ_KJPZ\"c/_onjPo<0G<Yun?9rfdT#a$9AUY0jBi=i7@@Gq<gRC_6W!Q]_;snLX3a#!Rlsnh,\\\\!KN9.81:1Yskda(m\\\\/L/QT(5ZrH\"9*V#?Y8\"ki9>Bd]O)g\"=W8rlG3*P8&A]&`it^\"N,cVJO\"eJjeP2RJK_l&L,Y1$WEINdc1^9D@FGeH=~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074274 00000 n \\n0000074723 00000 n \\n0000074991 00000 n \\n0000075060 00000 n \\n0000075344 00000 n \\n0000075410 00000 n \\n0000076791 00000 n \\ntrailer\\n<<\\n/ID \\n[<d0408224eb71c142dbc5a82b86143d57><d0408224eb71c142dbc5a82b86143d57>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77414\\n%%EOF\\n'\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_calib_pdf.py:261: in test_pdf_signature_verification\n    pytest.fail(f\"Erreur vérification signature: {str(e)}\")\nE   Failed: Erreur vérification signature: Hash SHA-256 manquant dans le PDF: e0aa81a413379ce6\nE   assert 'e0aa81a413379ce6' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73437 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVoQ*\"f3V9m\"jk4oM_3+,#tWc/Hc4;\\'9snf_1kjPXoX5I8O<_`6\\'5J?#VDUo6OaSf\"Hnl\\'ZTJ2n\\\\MtJ8ATs?oalL+LB:h;U4*U/K4n%h*H$=1h,QIfEzzzzzzzzzzzzzzzzzzzzzzzzJ<J*5\\'e:V+SG;9>J#_=e_TC\\'ISM=UYoenop>j]6*z!2+VGCtV^`9UU5\"l<V,O=m`p;cIfC3h;$f>[r7n0SZR\\'Bz!!$sYn%SZOA]\")K(u)]Fku,cp260`XG3$`,@VjUHD;2Lqr_K%DdGYj!DVRe.V/bP88P)LmdNrOZ<3UK/;JQ#...N~>endstream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 532\\n>>\\nstream\\nGat=\\'95i<6&AI=/b]/P?n\\'(R?2^jn3W_/(<E9P84m+!;cTi&85+5<mN/l7G*OXs-HchHpA!mF)Um72\\\\N/Z^T3LnRO.8gnAViBuAT20A3W?8/Vbj[a(P.::8rdMq.%WnPDJ$6uZ7:2SRKdl`)M3^K<3!M)ZU3mHlYeh0Ko4t>U*7!LpRT5m)h)&C557T&:[mdCVU.3HAS4Ym@eL91Y\\':\"d=pD6cQU:n@9==YXQk<O\"\\'#=.a]kI96u#KU]l(.lGS`]0e]5p)CAWMB1$*7/MYT#nRoG@dE\\\\?3%T#NCYi[AX1.8nc)+t\"(T7cnLaMq(.ILL,U@m`]OHQskWh)&%jMTo=B/<(9OQN.IVJ_KJPZ\"c/_onjPo<0G<Yun?9rfdT#a$9AUY0jBi=i7@@Gq<gRC_6W!Q]_;snLX3a#!Rlsnh,\\\\!KN9.81:1Yskda(m\\\\/L/QT(5ZrH\"9*V#?Y8\"ki9>Bd]O)g\"=W8rlG3*P8&A]&`it^\"N,cVJO\"eJjeP2RJK_l&L,Y1$WEINdc1^9D@FGeH=~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074274 00000 n \\n0000074723 00000 n \\n0000074991 00000 n \\n0000075060 00000 n \\n0000075344 00000 n \\n0000075410 00000 n \\n0000076791 00000 n \\ntrailer\\n<<\\n/ID \\n[<d0408224eb71c142dbc5a82b86143d57><d0408224eb71c142dbc5a82b86143d57>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77414\\n%%EOF\\n'\n____________________ TestCalibPDF.test_pdf_error_handling _____________________\ntests_smoke\\test_calib_pdf.py:271: in test_pdf_error_handling\n    with pytest.raises(Exception):\nE   Failed: DID NOT RAISE <class 'Exception'>\n-------------------------- Captured stdout teardown ---------------------------\n\n=== Nettoyage environnement de test ===\n=========================== short test summary info ===========================\nFAILED tests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_content_verification\nFAILED tests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_signature_verification\nFAILED tests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_error_handling\n========================= 3 failed, 3 passed in 4.60s =========================\n",
      "error": ""
    }
  }
}